# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/KashCherry/Documents/GitHub/Timer-Fix-plugin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/KashCherry/Documents/GitHub/Timer-Fix-plugin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/KashCherry/Documents/GitHub/Timer-Fix-plugin/CMakeFiles /mnt/c/Users/KashCherry/Documents/GitHub/Timer-Fix-plugin/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/KashCherry/Documents/GitHub/Timer-Fix-plugin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named timerfix

# Build rule for target.
timerfix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timerfix
.PHONY : timerfix

# fast build rule for target.
timerfix/fast:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/build
.PHONY : timerfix/fast

lib/sdk/amx/getch.o: lib/sdk/amx/getch.c.o

.PHONY : lib/sdk/amx/getch.o

# target to build an object file
lib/sdk/amx/getch.c.o:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/lib/sdk/amx/getch.c.o
.PHONY : lib/sdk/amx/getch.c.o

lib/sdk/amx/getch.i: lib/sdk/amx/getch.c.i

.PHONY : lib/sdk/amx/getch.i

# target to preprocess a source file
lib/sdk/amx/getch.c.i:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/lib/sdk/amx/getch.c.i
.PHONY : lib/sdk/amx/getch.c.i

lib/sdk/amx/getch.s: lib/sdk/amx/getch.c.s

.PHONY : lib/sdk/amx/getch.s

# target to generate assembly for a file
lib/sdk/amx/getch.c.s:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/lib/sdk/amx/getch.c.s
.PHONY : lib/sdk/amx/getch.c.s

lib/sdk/amxplugin.o: lib/sdk/amxplugin.cpp.o

.PHONY : lib/sdk/amxplugin.o

# target to build an object file
lib/sdk/amxplugin.cpp.o:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/lib/sdk/amxplugin.cpp.o
.PHONY : lib/sdk/amxplugin.cpp.o

lib/sdk/amxplugin.i: lib/sdk/amxplugin.cpp.i

.PHONY : lib/sdk/amxplugin.i

# target to preprocess a source file
lib/sdk/amxplugin.cpp.i:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/lib/sdk/amxplugin.cpp.i
.PHONY : lib/sdk/amxplugin.cpp.i

lib/sdk/amxplugin.s: lib/sdk/amxplugin.cpp.s

.PHONY : lib/sdk/amxplugin.s

# target to generate assembly for a file
lib/sdk/amxplugin.cpp.s:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/lib/sdk/amxplugin.cpp.s
.PHONY : lib/sdk/amxplugin.cpp.s

lib/sdk/amxplugin2.o: lib/sdk/amxplugin2.cpp.o

.PHONY : lib/sdk/amxplugin2.o

# target to build an object file
lib/sdk/amxplugin2.cpp.o:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/lib/sdk/amxplugin2.cpp.o
.PHONY : lib/sdk/amxplugin2.cpp.o

lib/sdk/amxplugin2.i: lib/sdk/amxplugin2.cpp.i

.PHONY : lib/sdk/amxplugin2.i

# target to preprocess a source file
lib/sdk/amxplugin2.cpp.i:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/lib/sdk/amxplugin2.cpp.i
.PHONY : lib/sdk/amxplugin2.cpp.i

lib/sdk/amxplugin2.s: lib/sdk/amxplugin2.cpp.s

.PHONY : lib/sdk/amxplugin2.s

# target to generate assembly for a file
lib/sdk/amxplugin2.cpp.s:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/lib/sdk/amxplugin2.cpp.s
.PHONY : lib/sdk/amxplugin2.cpp.s

src/core.o: src/core.cpp.o

.PHONY : src/core.o

# target to build an object file
src/core.cpp.o:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/core.cpp.o
.PHONY : src/core.cpp.o

src/core.i: src/core.cpp.i

.PHONY : src/core.i

# target to preprocess a source file
src/core.cpp.i:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/core.cpp.i
.PHONY : src/core.cpp.i

src/core.s: src/core.cpp.s

.PHONY : src/core.s

# target to generate assembly for a file
src/core.cpp.s:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/core.cpp.s
.PHONY : src/core.cpp.s

src/gettime.o: src/gettime.cpp.o

.PHONY : src/gettime.o

# target to build an object file
src/gettime.cpp.o:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/gettime.cpp.o
.PHONY : src/gettime.cpp.o

src/gettime.i: src/gettime.cpp.i

.PHONY : src/gettime.i

# target to preprocess a source file
src/gettime.cpp.i:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/gettime.cpp.i
.PHONY : src/gettime.cpp.i

src/gettime.s: src/gettime.cpp.s

.PHONY : src/gettime.s

# target to generate assembly for a file
src/gettime.cpp.s:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/gettime.cpp.s
.PHONY : src/gettime.cpp.s

src/hook.o: src/hook.cpp.o

.PHONY : src/hook.o

# target to build an object file
src/hook.cpp.o:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/hook.cpp.o
.PHONY : src/hook.cpp.o

src/hook.i: src/hook.cpp.i

.PHONY : src/hook.i

# target to preprocess a source file
src/hook.cpp.i:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/hook.cpp.i
.PHONY : src/hook.cpp.i

src/hook.s: src/hook.cpp.s

.PHONY : src/hook.s

# target to generate assembly for a file
src/hook.cpp.s:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/hook.cpp.s
.PHONY : src/hook.cpp.s

src/interface.o: src/interface.cpp.o

.PHONY : src/interface.o

# target to build an object file
src/interface.cpp.o:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/interface.cpp.o
.PHONY : src/interface.cpp.o

src/interface.i: src/interface.cpp.i

.PHONY : src/interface.i

# target to preprocess a source file
src/interface.cpp.i:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/interface.cpp.i
.PHONY : src/interface.cpp.i

src/interface.s: src/interface.cpp.s

.PHONY : src/interface.s

# target to generate assembly for a file
src/interface.cpp.s:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/interface.cpp.s
.PHONY : src/interface.cpp.s

src/internal.o: src/internal.cpp.o

.PHONY : src/internal.o

# target to build an object file
src/internal.cpp.o:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/internal.cpp.o
.PHONY : src/internal.cpp.o

src/internal.i: src/internal.cpp.i

.PHONY : src/internal.i

# target to preprocess a source file
src/internal.cpp.i:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/internal.cpp.i
.PHONY : src/internal.cpp.i

src/internal.s: src/internal.cpp.s

.PHONY : src/internal.s

# target to generate assembly for a file
src/internal.cpp.s:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/internal.cpp.s
.PHONY : src/internal.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/natives.o: src/natives.cpp.o

.PHONY : src/natives.o

# target to build an object file
src/natives.cpp.o:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/natives.cpp.o
.PHONY : src/natives.cpp.o

src/natives.i: src/natives.cpp.i

.PHONY : src/natives.i

# target to preprocess a source file
src/natives.cpp.i:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/natives.cpp.i
.PHONY : src/natives.cpp.i

src/natives.s: src/natives.cpp.s

.PHONY : src/natives.s

# target to generate assembly for a file
src/natives.cpp.s:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/natives.cpp.s
.PHONY : src/natives.cpp.s

src/timer.o: src/timer.cpp.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) -f CMakeFiles/timerfix.dir/build.make CMakeFiles/timerfix.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... timerfix"
	@echo "... lib/sdk/amx/getch.o"
	@echo "... lib/sdk/amx/getch.i"
	@echo "... lib/sdk/amx/getch.s"
	@echo "... lib/sdk/amxplugin.o"
	@echo "... lib/sdk/amxplugin.i"
	@echo "... lib/sdk/amxplugin.s"
	@echo "... lib/sdk/amxplugin2.o"
	@echo "... lib/sdk/amxplugin2.i"
	@echo "... lib/sdk/amxplugin2.s"
	@echo "... src/core.o"
	@echo "... src/core.i"
	@echo "... src/core.s"
	@echo "... src/gettime.o"
	@echo "... src/gettime.i"
	@echo "... src/gettime.s"
	@echo "... src/hook.o"
	@echo "... src/hook.i"
	@echo "... src/hook.s"
	@echo "... src/interface.o"
	@echo "... src/interface.i"
	@echo "... src/interface.s"
	@echo "... src/internal.o"
	@echo "... src/internal.i"
	@echo "... src/internal.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/natives.o"
	@echo "... src/natives.i"
	@echo "... src/natives.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

